name: tinder_clone
description: A Tinder clone app.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  card_swiper: ^2.0.4
  font_awesome_flutter: ^10.1.0
  firebase_core: ^2.10.0        # Core de Firebase (requerido)
  firebase_auth: ^4.6.0         # Autenticación con Firebase
  cloud_firestore: ^4.8.0       # Base de datos en la nube de Firebase

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
